name: PHP Intelephense

on:
  push:
    branches:
      - main

jobs:
  php-intelephense:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install PHP Intelephense
      run: code --install-extension bmewburn.vscode-intelephense-client --force
    - name: Run PHP Intelephense
      run: php index.php
