name: PHP Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Dependencies
      run: composer install

    - name: Code Style Check
      run: vendor/bin/phpcs

    - name: Run Tests
      run: vendor/bin/phpunit

    - name: Install PHP Intelliphence
      run: code --install-extension bmewburn.vscode-intelephense-client

    - name: Check PHP Intelliphence Installation
      run: code --list-extensions | grep bmewburn.vscode-intelephense-client
